// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qn7fKcTcn0ZkYCFm1nOAiyqNn6V1_pA',
    appId: '1:535711749588:web:dba5c3e30fd1ddc9987241',
    messagingSenderId: '535711749588',
    projectId: 'forjcalender',
    authDomain: 'forjcalender.firebaseapp.com',
    storageBucket: 'forjcalender.firebasestorage.app',
    measurementId: 'G-SEFD6KRVJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh28EFAIhLt-ScGfrzhQT1yqE1_Q2W-Y8',
    appId: '1:535711749588:android:2314d1164c813807987241',
    messagingSenderId: '535711749588',
    projectId: 'forjcalender',
    storageBucket: 'forjcalender.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkKLnFGG3d7IdYASQENUz6TKfPYmlAvpQ',
    appId: '1:535711749588:ios:be3d8efa6e5f4803987241',
    messagingSenderId: '535711749588',
    projectId: 'forjcalender',
    storageBucket: 'forjcalender.firebasestorage.app',
    iosClientId: '535711749588-qkhvobk9vhm6r3dgm9bm6j6m0urm08gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkKLnFGG3d7IdYASQENUz6TKfPYmlAvpQ',
    appId: '1:535711749588:ios:be3d8efa6e5f4803987241',
    messagingSenderId: '535711749588',
    projectId: 'forjcalender',
    storageBucket: 'forjcalender.firebasestorage.app',
    iosClientId: '535711749588-qkhvobk9vhm6r3dgm9bm6j6m0urm08gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qn7fKcTcn0ZkYCFm1nOAiyqNn6V1_pA',
    appId: '1:535711749588:web:c62df56db0296287987241',
    messagingSenderId: '535711749588',
    projectId: 'forjcalender',
    authDomain: 'forjcalender.firebaseapp.com',
    storageBucket: 'forjcalender.firebasestorage.app',
    measurementId: 'G-9BWTDW52NG',
  );
}
